import Head from 'next/head';
import styled from 'styled-components';

const Hero = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;

  height: 90vh;

  background: #fff;
`;

const Heading = styled.h1`
  font-size: 10rem;
  font-weight: 900;
  color: #000;
`;

export default function About() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>About</Heading>
      </Hero>
    </div>
  );
}
