import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Contact</h1>
    </div>
  );
}
